# Generated by Django 6.0.6 on 2026-06-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('categoria', models.CharField(help_text='Ej: Desechable, Recargable, Pod', max_length=100, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('especificaciones', models.CharField(blank=True, help_text='Ej: Puffs: 5000 | Nicotina: 5% | Batería: 650mAh', max_length=300, verbose_name='Especificaciones')),
                ('precio', models.CharField(help_text='Ej: $65.000', max_length=50, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vapes/', verbose_name='Imagen')),
                ('imagen_url', models.URLField(blank=True, help_text='Usa esto si no subes imagen', verbose_name='URL de imagen externa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vape',
                'verbose_name_plural': 'Vapes',
            },
        ),
    ]
